flowchart TD
    classDef actor fill:#08427b,stroke:#000,color:#fff,stroke-width:2px;
    classDef system fill:#1168bd,stroke:#000,color:#fff;
    classDef container fill:#4DA0FF,stroke:#000,color:#fff;
    classDef external fill:#999,stroke:#333,color:#fff;

    subgraph group_internal_0["📦 RAG collector"]
        direction TB
        scheduler["📋Planner<br/>[System]<br/>"]:::system
        subgraph group_internal_1["Primary processing"]
            detect["Type detector<br/>[LangGraph]<br/>Define a MIME type/format to select a partitioning strategy."]:::container
            exact_dedup["Dedup checker<br/>[LangGraph,Redis]<br/>Calculating the SHA-256 of a raw file; searching for uniqueness in the document hash repository."]:::container
            partition["Partition<br/>[LangGraph]<br/>Convert a document of any format into a unified list of structured elements."]:::container
            quality["Assess quality<br/>[LLM,LangGraph]<br/>Evaluation of structural integrity, completeness of extraction, and linguistic consistency."]:::container
            hitl["👤 HITL service<br/>[Mattermost, IDE]<br/>Approvals, risk management"]:::container
        end
        chunking["Chunking<br/>[LLM,LangGraph,BGE]<br/>Chunking, duplicate checking, metadata generation, enrichment, and vectorization."]:::container
    end

    scheduler --> detect
    detect --> exact_dedup --> partition --> quality
    quality -->|"Low-quality documents/duplicates for manual review"| hitl
    quality --> chunking

    style group_internal_0 stroke:#555,stroke-dasharray: 5 5,fill:#f9f9f9,fill-opacity:0.8;
    style group_internal_1 stroke:#555,stroke-dasharray: 5 5,fill:#f9f9f9,fill-opacity:0.8;